### ISSUE TITLE
请问为什么会有这个报错呢？java.lang.UnsatisfiedLinkError: dlopen failed: library "liblipsync.so" not found

### ISSUE THREAD

**Issue by KaiJiaBrother** [Voine/ChatWaifu_Mobile#16]
FATAL EXCEPTION: main
                                                                                                    Process: com.chatwaifu.mobile, PID: 8355
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "liblipsync.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.chatwaifu.lipsync.LipSyncJNI.<clinit>(LipSyncJNI.kt:37)
                                                                                                    	at com.chatwaifu.mobile.utils.LipsValueHandler.<init>(LipsValueHandler.kt:62)
                                                                                                    	at com.chatwaifu.mobile.ChatActivityViewModel$lipsValueHandler$2.invoke(ChatActivityViewModel.kt:79)
                                                                                                    	at com.chatwaifu.mobile.ChatActivityViewModel$lipsValueHandler$2.invoke(ChatActivityViewModel.kt:78)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.chatwaifu.mobile.ChatActivityViewModel.getLipsValueHandler(ChatActivityViewModel.kt:78)
                                                                                                    	at com.chatwaifu.mobile.ChatActivityViewModel.initModel(ChatActivityViewModel.kt:151)
                                                                                                    	at com.chatwaifu.mobile.ui.channellist.ChannelListFragment.onViewCreated(ChannelListFragment.kt:80)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
                                                                                                    	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
                                                                                                    	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
                                                                                                    	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
                                                                                                    	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
                                                                                                    	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
                                                                                                    	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                                                                                    	at com.chatwaifu.mobile.databinding.ContentMainBinding.inflate(ContentMainBinding.java:45)
                                                                                                    	at com.chatwaifu.mobile.ui.base.ComposableSingletons$ChatWaifuMainContentKt$lambda-1$1$1.invoke(ChatWaifuMainContent.kt:86)
                                                                                                    	at com.chatwaifu.mobile.ui.base.ComposableSingletons$ChatWaifuMainContentKt$lambda-1$1$1.invoke(ChatWaifuMainContent.kt:86)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewBindingKt$AndroidViewBinding$viewBlock$1$1.invoke(AndroidViewBinding.kt:83)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewBindingKt$AndroidViewBinding$viewBlock$1$1.invoke(AndroidViewBinding.kt:79)
                                                                                                    	at androidx.compose.ui.viewinterop.ViewFactoryHolder.<init>(AndroidView.android.kt:314)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidView_androidKt$createAndroidViewNodeFactory$1.invoke(AndroidView.android.kt:247)

**Comment by Voine** [comment]
x86 模拟器不支持，lipsync 只有 armv7 armv8 两种类型的依赖
